Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot QC figures

if sys.platform == 'darwin':
    # For local testing on OSX    
    sct_deepseg_sc_qc = 'qc/sct_example_data/mt/sct_deepseg_sc'
else:
    # For linux and on-line Binder execution
    sct_deepseg_sc_qc = join(qc_path, parent_dirs[-1], mt_folder_relative, 'sct_deepseg_sc')

folders = list(filter(lambda x: os.path.isdir(os.path.join(sct_deepseg_sc_qc, x)), os.listdir(sct_deepseg_sc_qc)))

qc_date = max(folders)

sct_deepseg_sc_qc_dir = join(sct_deepseg_sc_qc, qc_date)

bkg = mpimg.imread(join(sct_deepseg_sc_qc_dir, 'bkg_img.png'))
overlay = mpimg.imread(join(sct_deepseg_sc_qc_dir, 'overlay_img.png'))
plt.figure(figsize = (20,2))
plt.axis('off')
imgplot = plt.imshow(bkg)
imgplot = plt.imshow(overlay,alpha=0.3)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[8], line 10[0m
[1;32m      6[0m [38;5;28;01melse[39;00m:
[1;32m      7[0m     [38;5;66;03m# For linux and on-line Binder execution[39;00m
[1;32m      8[0m     sct_deepseg_sc_qc [38;5;241m=[39m join(qc_path, parent_dirs[[38;5;241m-[39m[38;5;241m1[39m], mt_folder_relative, [38;5;124m'[39m[38;5;124msct_deepseg_sc[39m[38;5;124m'[39m)
[0;32m---> 10[0m folders [38;5;241m=[39m [38;5;28mlist[39m([38;5;28mfilter[39m([38;5;28;01mlambda[39;00m x: os[38;5;241m.[39mpath[38;5;241m.[39misdir(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(sct_deepseg_sc_qc, x)), [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43msct_deepseg_sc_qc[49m[43m)[49m))
[1;32m     12[0m qc_date [38;5;241m=[39m [38;5;28mmax[39m(folders)
[1;32m     14[0m sct_deepseg_sc_qc_dir [38;5;241m=[39m join(sct_deepseg_sc_qc, qc_date)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/storage/tmp/tmph8791azm/qc/tmph8791azm/sct_example_data/mt/sct_deepseg_sc'

